// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yolyuoofgbsxwhefvvcs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvbHl1b29mZ2JzeHdoZWZ2dmNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MjE2NDIsImV4cCI6MjA2NjA5NzY0Mn0.7dfNdGleiIBNBXnE0gR16oV_Y-XrjPI2ps8ysxV0XPQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);